package com.nsteuerberg.simondice

import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.ui.graphics.Color

/**
 * Class that contains the data of the game
 * @property round actual round
 * @property roundState state of the round
 * @property UserSecuence user secuence introduced by the user
 * @property botSecuence bot secuence generated by the bot
 * @property record record of the game
 *
 */
object Data {
    var round = mutableStateOf(0)
    var playStatus = mutableStateOf("Start")
    var UserSecuence = mutableListOf<Int>()
    var botSecuence = mutableListOf<Int>()
    var record = mutableStateOf(0)
    var state = State.START
    var colors = listOf(Color.Red, Color.Blue, Color.Green, Color.Yellow)
}

/**
 * Enum class that contains the colors of the game
 * @property value value of the color
 */
enum class MyColors(color: Color) {
    RED(Color.Red),
    BLUE(Color.Blue),
    GREEN(Color.Green),
    YELLOW(Color.Yellow)
}

/**
 * Enum class that contains the states of the game
 */
enum class State {
    START,
    SEQUENCE,
    WAITING,
    INPUT,
    CHECKING,
    FINISH
}

